name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-11-arm]
        sys: [clangarm64]
        mode: [dynamic, static]
    runs-on: ${{ matrix.os }}
    env:
      dynamic_flags: '--enable-gtk'
      static_flags: '--disable-gtk --disable-spice --disable-usb-redir --disable-smartcard --disable-gnutls --disable-libssh --disable-vnc-sasl --static'
      static_extra_cflags: '-DCURL_STATICLIB -DLIBSSH_STATIC -DLIBSLIRP_STATIC -DCAIRO_WIN32_STATIC_BUILD'
      clang_extra_cflags: '-Wno-missing-prototypes -Wno-sometimes-uninitialized -Wno-pragma-pack'

    name: ${{ format('🚧 {0} Build {1}', matrix.sys, matrix.mode) }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@main

    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          git
          make
          bison
          diffutils
          flex
          base-devel
          python
          python-setuptools
        pacboy: >-
          toolchain:p
          binutils:p
          capstone:p
          ccache:p
          curl:p
          cyrus-sasl:p
          dtc:p
          gcc:p
          glib2:p
          gnutls:p
          gtk3:p
          libgcrypt:p
          libjpeg-turbo:p
          libnfs:p
          libpng:p
          libssh:p
          libtasn1:p
          libusb:p
          lzo2:p
          nettle:p
          ninja:p
          pixman:p
          pkgconf:p
          python:p
          SDL2:p
          SDL2_image:p
          snappy:p
          spice:p
          usbredir:p
          zstd:p
          libslirp:p
          python-distlib:p
          nsis:c

    - name: 'Modify pkgconfig to avoid linker issues'
      if: ${{ matrix.mode == 'static' }}
      run: |
          PKGCONFIG_FILE="/${{ matrix.sys }}/lib/pkgconfig/gpg-error.pc"
          sed -i "s#/${{ matrix.sys }}/lib/libintl.dll.a#-llibintl#g" "$PKGCONFIG_FILE"
          sed -i "s#/${{ matrix.sys }}/lib/libiconv.dll.a#-llibiconv#g" "$PKGCONFIG_FILE"

    - name: ${{ format ('🚧 Build QEMU (arm & aarch64) {0}', matrix.mode) }}
      env:
        mode_flags: ${{ matrix.mode == 'dynamic' && env.dynamic_flags || env.static_flags }}
        extra_cflags: ${{ (matrix.mode == 'static' || startsWith(matrix.sys, 'clang')) && format('--extra-cflags="{0} {1}"', matrix.mode == 'static' && env.static_extra_cflags || '', startsWith(matrix.sys, 'clang') && env.clang_extra_cflags || '') || '' }}
      run: |
          ./configure --enable-sdl --enable-fdt=system --disable-docs --target-list=arm-softmmu,aarch64-softmmu --prefix="$(cygpath -u '${{ github.workspace }}')/artifacts" ${{ format('{0} {1}', env.mode_flags, env.extra_cflags) }}
          make -j16
          echo "version=v$(cat VERSION)-$(git rev-parse --short HEAD)" > $GITHUB_ENV

    - name: 'Workaround for clangarm64 nsis'
      if: ${{ matrix.mode == 'dynamic' }}
      run: |
          ln -d -s /clang64/share/nsis /clangarm64/share/nsis
          ln /clang64/etc/nsisconf.nsh /clangarm64/etc/nsisconf.nsh
          ln /clang64/bin/makensis.exe /clangarm64/bin/makensis.exe

    - name: 'Prepare Artifacts (static)'
      if: ${{ matrix.mode == 'static' }}
      run: |
          make install

    - name: 'Prepare Artifacts (dynamic)'
      if: ${{ matrix.mode == 'dynamic' }}
      run: |
          make installer
          mv -v build/qemu-setup*.exe qemu-setup-${version}.exe;

    - name: 'Upload artifact (dynamic)'
      if: ${{ matrix.mode == 'dynamic' }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ format('QEMU {0} (Windows ARM64 {1} build)', env.version, matrix.mode) }}
        path: ${{ github.workspace }}\qemu-setup-${{ env.version }}.exe
        compression-level: 9

    - name: 'Upload artifact (static)'
      if: ${{ matrix.mode == 'static' }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ format('QEMU {0} (Windows ARM64 {1} build)', env.version, matrix.mode) }}
        path: ${{ github.workspace }}\artifacts
        compression-level: 9

    - name: 'Upload logs'
      if: ${{ failure() }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ format('QEMU {0} (Windows ARM64 {1} build) logs', env.version, matrix.mode) }}
        path: ${{ github.workspace }}/build
        compression-level: 9
